### ISSUE TITLE
Testing result of Animals mod

### ISSUE THREAD

**Issue by rahuselama** [yum-feng/COMP5541TeamZombieCode#7]
When the animal is dropped (it looks like it is dropped too close to the player and it causes that the item is automatically picked up by the player ) so it does not stay . If the player after dropping the item goes back, the items stays. Is it possible to modify the dropping distance ? So that item is dropped further away from the player ?

**Comment by acpears** [comment]
The issue I believe arises from how you drop the item and not with the code. All items act this way already in the game!
