### ISSUE TITLE
>Research for Static code analysis Tool

### ISSUE THREAD

**Issue by rahuselama** [yum-feng/COMP5541TeamZombieCode#8]
> Going forward, try to remove all unused imports. In eclipse, it shows several of them are not required. Also, if vars, objects or code is not being used remove it completely instead of applying comments. Thank you!

A static code analysis tool should be able to catch unused imports. Would be interesting if one of the testers looked into setting one up.

_Originally posted by @yum-feng in https://github.com/yum-feng/COMP5541TeamZombieCode/issues/5#issuecomment-1038472324_

**Comment by rahuselama** [comment]
Adriana, could you please have a look into finding a static code analysis tool should be able to catch unused imports?
Thank you !

**Comment by adrianadanko** [comment]
Yes, on it
